function FIZ_InitEnFactions()		
--Alliance		
--Aliance Cities		
	FIZ_AddMapping("Darnassus", 69)	
	FIZ_AddMapping("Exodar", 930)	
	FIZ_AddMapping("Gilneas", 1134)	
	FIZ_AddMapping("Gnomeregan", 54)	
	FIZ_AddMapping("Ironforge", 47)	
	FIZ_AddMapping("Stormwind", 72)	
	FIZ_AddMapping("Tushui Pandaren", 1353)	
--Alliance Forces		
	FIZ_AddMapping("Silverwing Sentinels", 890)	
	FIZ_AddMapping("Stormpike Guard", 730)	
	FIZ_AddMapping("The League of Arathor", 509)	
	FIZ_AddMapping("Bizmo's Brawlpub", 1419)	
--Outlands(alliance)		
	FIZ_AddMapping("Honor Hold", 946)	
	FIZ_AddMapping("Kurenai", 978)	
--Alliance Vanguard		
	FIZ_AddMapping("Alliance Vanguard", 1037)	
	FIZ_AddMapping("Explorers' League", 1068)	
	FIZ_AddMapping("The Frostborn", 1126)	
	FIZ_AddMapping("The Silver Covenant", 1094)	
	FIZ_AddMapping("Valiance Expedition", 1050)	
--Cataclysm		
	FIZ_AddMapping("Wildhammer Clan", 1174)	
	FIZ_AddMapping("Baradin's Wardens", 1177)	
--Mist Of Panderia		
	FIZ_AddMapping("Pearlfin Jinyu", 1242)	
	FIZ_AddMapping("Operation: Shieldwall", 1376)	
	FIZ_AddMapping("Kirin Tor Offensive", 1387)	
--Horde		
--Hord Cities		
	FIZ_AddMapping("Darkspear Trolls", 530)	
	FIZ_AddMapping("Orgrimmar", 76)	
	FIZ_AddMapping("Silvermoon City", 911)	
	FIZ_AddMapping("Thunder Bluff", 81)	
	FIZ_AddMapping("Undercity", 68)	
	FIZ_AddMapping("Bilgewater Cartel", 1133)	
	FIZ_AddMapping("Huojin Pandaren", 1352)	
--Horde Forces		
	FIZ_AddMapping("Brawl'gar Arena", 1374)	
	FIZ_AddMapping("Frostwolf Clan", 729)	
	FIZ_AddMapping("The Defilers", 510)	
	FIZ_AddMapping("Warsong Outriders", 889)	
--outland		
	FIZ_AddMapping("Thrallmar", 947)	
	FIZ_AddMapping("The Mag'har", 941)	
	FIZ_AddMapping("Tranquillien", 922)	
--Horde Expedition		
	FIZ_AddMapping("Horde Expedition", 1052)	
	FIZ_AddMapping("The Hand of Vengeance", 1067)	
	FIZ_AddMapping("The Sunreavers", 1124)	
	FIZ_AddMapping("Warsong Offensive", 1085)	
	FIZ_AddMapping("The Taunka", 1064)	
--Cataclysm		
	FIZ_AddMapping("Dragonmaw Clan", 1172)	
	FIZ_AddMapping("Hellscream's Reach", 1178)	
--Mist Of Panderia		
	FIZ_AddMapping("Forest Hozen", 1228)	
	FIZ_AddMapping("Dominance Offensive", 1375)	
	FIZ_AddMapping("Sunreaver Onslaught", 1388)	
--Steamwheedle Cartel		
	FIZ_AddMapping("Booty Bay", 21)	
	FIZ_AddMapping("Everlook", 577)	
	FIZ_AddMapping("Gadgetzan", 369)	
	FIZ_AddMapping("Ratchet", 470)	
	FIZ_AddMapping("Bloodsail Buccaneers", 87)	
--Classic		
	FIZ_AddMapping("Argent Dawn", 529)	
	FIZ_AddMapping("Darkmoon Faire", 909)	
	FIZ_AddMapping("Ravenholdt", 349)	
	FIZ_AddMapping("Syndicate", 70)	
	FIZ_AddMapping("Thorium Brotherhood", 59)	
	FIZ_AddMapping("Timbermaw Hold", 576)	
	FIZ_AddMapping("Wintersaber Trainers", 589)	
--Raid		
	FIZ_AddMapping("Ashtongue Deathsworn", 1012)	
	FIZ_AddMapping("Brood of Nozdormu", 910)	
	FIZ_AddMapping("Cenarion Circle", 609)	
	FIZ_AddMapping("Hydraxian Waterlords", 749)	
	FIZ_AddMapping("The Scale of the Sands", 990)	
	FIZ_AddMapping("The Violet Eye", 967)	
--outland		
	FIZ_AddMapping("Cenarion Expedition", 942)	
	FIZ_AddMapping("Keepers of Time", 989)	
	FIZ_AddMapping("Netherwing", 1015)	
	FIZ_AddMapping("Ogri'la", 1038)	
	FIZ_AddMapping("Sha'tari Skyguard", 1031)	
	FIZ_AddMapping("Sporeggar", 970)	
	FIZ_AddMapping("The Consortium", 933)	
--Shattrath City		
	FIZ_AddMapping("Lower City", 1011)	
	FIZ_AddMapping("Shattered Sun Offensive", 1077)	
	FIZ_AddMapping("The Aldor", 932)	
	FIZ_AddMapping("The Scryers", 934)	
	FIZ_AddMapping("The Sha'tar", 935)	
--Wrath of the Lich King (WotLK)		
	FIZ_AddMapping("Argent Crusade", 1106)	
	FIZ_AddMapping("Kirin Tor", 1090)	
	FIZ_AddMapping("Knights of the Ebon Blade", 1098)	
	FIZ_AddMapping("The Ashen Verdict", 1156)	
	FIZ_AddMapping("The Kalu'ak", 1073)	
	FIZ_AddMapping("The Sons of Hodir", 1119)	
	FIZ_AddMapping("The Wyrmrest Accord", 1091)	
	FIZ_AddMapping("Frenzyheart Tribe", 1104)	
	FIZ_AddMapping("The Oracles", 1105)	
--Cataclysm		
	FIZ_AddMapping("Avengers of Hyjal", 1204)	
	FIZ_AddMapping("Guardians of Hyjal", 1158)	
	FIZ_AddMapping("Ramkahen", 1173)	
	FIZ_AddMapping("The Earthen Ring", 1135)	
	FIZ_AddMapping("Therazane", 1171)	
--Mist of Pandarea		
	FIZ_AddMapping("Golden Lotus", 1269)	
	FIZ_AddMapping("Order of the Cloud Serpent", 1271)	
	FIZ_AddMapping("Shado-Pan", 1270)	
	FIZ_AddMapping("Shang Xi's Academy", 1216)	
	FIZ_AddMapping("The August Celestials", 1341)	
	FIZ_AddMapping("The Black Prince", 1359)	
	FIZ_AddMapping("The Brewmasters", 1351)	
	FIZ_AddMapping("The Klaxxi", 1337)	
	FIZ_AddMapping("The Lorewalkers", 1345)	
	FIZ_AddMapping("Akama's Trust", 1416)	
--ver 5.04		
	FIZ_AddMapping("Emperor Shaohao", 1492)	
--The Anglers		
	FIZ_AddMapping("The Anglers", 1302)	
	FIZ_AddMapping("Nat Pagle", 1358)	
--The Tillers		
	FIZ_AddMapping("The Tillers", 1272)	
	FIZ_AddMapping("Chee Chee", 1277)	
	FIZ_AddMapping("Ella", 1275)	
	FIZ_AddMapping("Farmer Fung", 1283)	
	FIZ_AddMapping("Fish Fellreed", 1282)	
	FIZ_AddMapping("Gina Mudclaw", 1281)	
	FIZ_AddMapping("Haohan Mudclaw", 1279)	
	FIZ_AddMapping("Jogu the Drunk", 1273)	
	FIZ_AddMapping("Old Hillpaw", 1276)	
	FIZ_AddMapping("Sho", 1278)	
	FIZ_AddMapping("Tina Mudclaw", 1280)	
--Dead Factions		
	FIZ_AddMapping("Shen'dralar", 809)	
	FIZ_AddMapping("Gelkis Clan Centaur", 92)	
	FIZ_AddMapping("Magram Clan Centaur", 93)	
	FIZ_AddMapping("Zandalar Tribe", 270)	
end